
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in
  - force_unwrapping
  - empty_count 
  - yoda_condition

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_try:
  severity: warning # explicitly
weak_delegate:
  severity: error # explicitly

# or they can set both explicitly
# file_length:
#   warning: 20
#   error: 100

# function_body_length:
#   warning: 5
#   error: 20